import math
import pygame as pg

# game settings
RES = WIDTH, HEIGHT = 1020,600 
# RES = WIDTH, HEIGHT = 1920, 108
HALF_WIDTH = WIDTH // 2
HALF_HEIGHT = HEIGHT // 2

FPS = 0

PLAYER_POS = 1.5, 5  # mini_map
PLAYER_ANGLE = 0
PLAYER_SPEED = 0.004
PLAYER_ROT_SPEED = 0.001
PLAYER_SIZE_SCALE = 60
PLAYER_MAX_HEALTH = 500

MOUSE_SENSITIVITY = 0.000002
MOUSE_MAX_REL = 100
MOUSE_BORDER_LEFT = 70
MOUSE_BORDER_RIGHT = WIDTH - MOUSE_BORDER_LEFT

FLOOR_COLOR = (91, 77, 47)

FOV = math.pi / 3
HALF_FOV = FOV / 2
NUM_RAYS = WIDTH // 2
HALF_NUM_RAYS = NUM_RAYS // 2
DELTA_ANGLE = FOV / NUM_RAYS
MAX_DEPTH = 20

SCREEN_DIST = HALF_WIDTH / math.tan(HALF_FOV)
SCALE = WIDTH // NUM_RAYS

TEXTURE_SIZE = 260
HALF_TEXTURE_SIZE = TEXTURE_SIZE // 2